version: "2"

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*_gen.go"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - unused
    - ineffassign
    - depguard

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: if-return
      - name: import-shadowing
  depguard:
    list-type: blacklist
    packages:
      - fmt
    packages-with-error-message:
      fmt: "Use your logger package instead of fmt"
